import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PWA Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>PWA em Next</h1>

        <p>Teste PWA</p>
      </main>
    </div>
  )
}
